const content = {
  nav: [
    { href: '#home', label: 'Home' },
    { href: '#projects', label: 'Projects' },
    { href: '#skills', label: 'Skills' },
    { href: '#testimonials', label: 'Testimonials' },
    { href: '#awards', label: 'Awards' },
    { href: '#experience', label: 'Experience' },
    { href: '#contact', label: 'Contact' },
  ],
  hero: {
    role: 'Senior Frontend Developer',
    heading: "Hi, I'm Vikash Kumar",
    description: 'Crafting exceptional digital experiences through clean code and innovative design. Specializing in React, TypeScript, and modern web technologies.',
    about: 'Senior software engineer with 8+ years of experience in IoT, medical imaging, and performance monitoring domains. Proficient in React.js, TypeScript, JavaScript and the full software development cycle, with a strong focus on delivering innovative solutions in healthcare technology.',
    aboutTitle: 'About Me',
    cta: {
      work: 'View My Work',
      contact: 'Get in Touch',
      resume: 'Download Resume',
      coverLetter: 'View Cover Letter',
      resumeUrl: '/vikash-kumar-resume.pdf',
    },
    social: [
      { href: 'https://github.com/vikashkuma', label: 'GitHub', aria: 'GitHub Profile' },
      { href: 'https://www.linkedin.com/in/vikash-kumar-verma/', label: 'LinkedIn', aria: 'LinkedIn Profile' },
      { href: 'https://x.com/RajaVicky007', label: 'Twitter/X', aria: 'Twitter/X Profile' },
    ],
    profilePhoto: {
      src: '/profile.jpg',
      alt: 'Vikash Kumar profile',
    },
    coverLetter: `Dear Hiring Manager,\n\nI am writing to express my interest in the Frontend Developer position at your esteemed organization. With over 8 years of experience in software engineering, I have developed a strong expertise in building innovative, scalable, and high-performance web applications, particularly in the domains of IoT, medical imaging, and performance monitoring.\n\nThroughout my career, I have demonstrated proficiency in React.js, TypeScript, JavaScript, and the full software development cycle. My recent role as a Senior Software Engineer at Catchpoint involved leading a team to design, develop, and deploy performance monitoring solutions using modern frameworks and technologies such as React, Redux, GraphQL, and Node.js. I have a proven track record of delivering user-centric applications, optimizing system performance, and mentoring junior developers to achieve project goals.\n\nMy experience also includes developing medical imaging solutions at Accure Pvt. Ltd., where I contributed to innovative healthcare applications, and building IoT platforms at Techchefs Software Pvt. Ltd., where I was responsible for UI development and API integration for smart home devices.\n\nI am passionate about staying at the forefront of technology, as evidenced by my participation in hackathons and continuous learning through courses in AI and ML. My technical skills are complemented by a strong foundation in Agile methodologies, user interface design, and a commitment to delivering high-quality software.\n\nI am excited about the opportunity to contribute my skills and experience to your team and help drive the success of your projects. Thank you for considering my application. I look forward to the possibility of discussing how I can add value to your organization.\n\nSincerely,\nVikash Kumar`,
    aboutSection: {
      title: 'About Me',
      description: 'Senior software engineer with 8+ years of experience in IoT, medical imaging, and performance monitoring domains. Proficient in React.js, TypeScript, JavaScript and the full software development cycle, with a strong focus on delivering innovative solutions in healthcare technology.'
    },
    scrollDown: 'Scroll Down',
  },
  skills: {
    tabs: [
      { label: 'Frontend', key: 'frontend' },
      { label: 'Backend', key: 'backend' },
      { label: 'DevOps/Deployment', key: 'devops' },
      { label: 'Testing', key: 'testing' },
      { label: 'AI/GenAI', key: 'ai' },
      { label: 'Others', key: 'others' },
    ],
    items: [
      { name: 'React', tab: 'frontend', proficiency: 95 },
      { name: 'Next.js', tab: 'frontend', proficiency: 90 },
      { name: 'TypeScript', tab: 'frontend', proficiency: 90 },
      { name: 'TailwindCSS', tab: 'frontend', proficiency: 85 },
      { name: 'Design Systems', tab: 'frontend', proficiency: 80 },
      { name: 'Accessibility', tab: 'frontend', proficiency: 80 },
      { name: 'Node.js', tab: 'backend', proficiency: 85 },
      { name: 'Express', tab: 'backend', proficiency: 80 },
      { name: 'MongoDB', tab: 'backend', proficiency: 80 },
      { name: 'PostgreSQL', tab: 'backend', proficiency: 70 },
      { name: 'REST', tab: 'backend', proficiency: 85 },
      { name: 'GraphQL', tab: 'backend', proficiency: 75 },
      { name: 'Docker', tab: 'devops', proficiency: 80 },
      { name: 'GitHub Actions', tab: 'devops', proficiency: 75 },
      { name: 'GitLab', tab: 'devops', proficiency: 70 },
      { name: 'Vercel', tab: 'devops', proficiency: 80 },
      { name: 'Netlify', tab: 'devops', proficiency: 75 },
      { name: 'Helm', tab: 'devops', proficiency: 60 },
      { name: 'Kubernetes', tab: 'devops', proficiency: 50 },
      { name: 'Jest', tab: 'testing', proficiency: 80 },
      { name: 'React Testing Library', tab: 'testing', proficiency: 75 },
      { name: 'Cypress', tab: 'testing', proficiency: 70 },
      { name: 'GPT-4 API', tab: 'ai', proficiency: 70 },
      { name: 'LangChain', tab: 'ai', proficiency: 60 },
      { name: 'RAG architecture basics', tab: 'ai', proficiency: 60 },
      { name: 'Prompt engineering', tab: 'ai', proficiency: 65 },
      { name: 'Git', tab: 'others', proficiency: 90 },
      { name: 'Webpack', tab: 'others', proficiency: 70 },
      { name: 'ESLint', tab: 'others', proficiency: 80 },
      { name: 'Storybook', tab: 'others', proficiency: 70 },
      { name: 'Firebase', tab: 'others', proficiency: 70 },
    ],
    proficiencyTitle: 'Tech Stack Proficiency',
  },
  experience: [
    {
      year: '2024',
      color: 'blue',
      title: 'Lead Software Development Engineer',
      org: 'EPAM Systems',
      time: 'Oct 2024 – Present · Bengaluru, Karnataka, India (Hybrid)',
      details: [
        'Leading development teams to deliver high-quality software solutions.',
        'Skills: Leading Development Teams',
      ],
    },
    {
      year: '2021',
      color: 'blue',
      title: 'Software Engineer III',
      org: 'Catchpoint',
      time: 'Dec 2021 – Oct 2024 · Bangalore Urban, Karnataka, India',
      details: [
        'Worked on performance monitoring and analytics solutions.',
        'Skills: JavaScript, React.js, TypeScript, Apollo GraphQL, Redux.js',
      ],
    },
    {
      year: '2019',
      color: 'blue',
      title: 'Software Engineer II',
      org: 'Catchpoint',
      time: 'Jun 2019 – Nov 2021 · Bengaluru, Karnataka, India',
      details: [
        'Full stack developer @ Catchpoint.',
        'Skills: JavaScript, React.js, TypeScript, Apollo GraphQL, Redux.js',
      ],
    },
    {
      year: '2018',
      color: 'blue',
      title: 'Software Engineer',
      org: 'Accure Inc.',
      time: 'Jun 2018 – May 2019 · Bangalore',
      details: [
        'Developed and integrated UI components for medical imaging solutions.',
        'Skills: JavaScript, React.js, Redux.js',
      ],
    },
    {
      year: '2016',
      color: 'blue',
      title: 'Associate Software Engineer',
      org: 'TechChefs Software Pvt Ltd',
      time: 'Jul 2016 – Jun 2018 · Bangalore',
      details: [
        'To enhance my career and contribute to software development projects.',
        'Skills: JavaScript',
      ],
    },
  ],
  education: [
    {
      year: '2015',
      color: 'purple',
      title: 'BTECH (CSE)',
      org: 'Future Institute of Engineering And Management, Kolkata',
      time: 'June 2011 — June 2015',
      details: ['CGPA: 7.53'],
    },
    {
      year: '2011',
      color: 'purple',
      title: 'Intermediate (Science)',
      org: '[Your School Name Here]',
      time: '2009 — 2011',
      details: [],
    },
    {
      year: '2009',
      color: 'purple',
      title: 'Metric',
      org: '[Your School Name Here]',
      time: '2007 — 2009',
      details: [],
    },
  ],
  projects: [
    {
      title: 'E-Commerce Platform',
      description: 'A full-stack e-commerce platform built with React, Node.js, and MongoDB. Features include real-time inventory, payment processing, and admin dashboard.',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
      demoLink: '#',
      githubLink: '#',
    },
    {
      title: 'Task Management App',
      description: 'A collaborative task management application with real-time updates, team features, and analytics dashboard.',
      image: 'https://images.unsplash.com/photo-1540350394557-8d14678e7f91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'TypeScript', 'Firebase', 'Tailwind'],
      demoLink: '#',
      githubLink: '#',
    },
    {
      title: 'AI-Powered Analytics',
      description: 'An analytics dashboard with AI-powered insights and predictions for business metrics.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'Python', 'TensorFlow', 'D3.js'],
      demoLink: '#',
      githubLink: '#',
    },
  ],
  testimonials: [
    {
      quote: 'Vikash is a highly skilled engineer who consistently delivers high-quality work. His attention to detail and ability to solve complex problems make him a valuable asset to any team.',
      name: 'Ankit Sharma',
      title: 'Engineering Manager, Catchpoint',
    },
    {
      quote: 'Working with Vikash was a pleasure. He brings innovative solutions to the table and is always willing to help others grow.',
      name: 'Priya Singh',
      title: 'Lead Developer, Accure Inc.',
    },
    {
      quote: "Vikash's expertise in frontend technologies and his leadership skills have been instrumental in the success of our projects.",
      name: 'Rahul Verma',
      title: 'Project Manager, EPAM Systems',
    },
  ],
  awards: [
    {
      icon: 'trophy',
      title: 'Hackathon Winner',
      description: 'Won multiple internal hackathons at Catchpoint for innovative solutions in performance monitoring and dashboard design.',
      date: '2022, 2023',
    },
    {
      icon: 'star',
      title: 'Employee of the Month',
      description: 'Recognized as Employee of the Month at Accure Inc. for outstanding contributions to medical imaging projects.',
      date: '2019',
    },
    {
      icon: 'academicCap',
      title: 'AI & ML Course Completion',
      description: 'Successfully completed AI and ML certification from Udemy, demonstrating commitment to continuous learning.',
      date: '2021',
    },
  ],
  certifications: [
    {
      name: 'AWS Certified Solutions Architect',
      org: 'Amazon Web Services',
      year: '2022',
    },
    {
      name: 'Google Professional Cloud Developer',
      org: 'Google Cloud',
      year: '2021',
    },
    {
      name: 'Scrum Master Certified (SMC)',
      org: 'Scrum Alliance',
      year: '2020',
    },
  ],
  contact: {
    heading: 'Contact',
    thankYou: 'Thank you for reaching out! I will get back to you soon.',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send Message',
  },
  projectsSection: {
    title: 'Featured Projects',
    description: 'A selection of my recent work showcasing my expertise in building modern web applications with a focus on user experience and performance.',
  },
};

export default content; 