const content = {
  nav: [
    { href: '#home', label: 'Home' },
    { href: '#projects', label: 'Projects' },
    { href: '#skills', label: 'Skills' },
    { href: '#testimonials', label: 'Testimonials' },
    { href: '#awards', label: 'Awards' },
    { href: '#experience', label: 'Experience' },
    { href: '#contact', label: 'Contact' },
  ],
  hero: {
    role: 'Lead Software Engineer',
    heading: "Hi, I'm Vikash Kumar",
    description: 'Leading teams to craft scalable, high-impact web solutions with a focus on performance, clean architecture, and intuitive UX.',
    about: 'Lead Software Engineer at EPAM Systems with 9+ years of industry experience. I specialize in leading frontend teams, crafting performant web platforms, and driving innovation in domains like fintech, healthcare, and IoT. My core focus lies in building robust, intuitive interfaces and mentoring developers to reach their peak potential.',
    aboutTitle: 'About Me',
    cta: {
      work: 'Explore My Work',
      contact: 'Let’s Connect',
      resume: 'Download Resume',
      coverLetter: 'View Cover Letter',
      resumeUrl: '/vikash-kumar-resume.pdf',
    },
    social: [
      { href: 'https://github.com/vikashkuma', label: 'GitHub', aria: 'GitHub Profile' },
      { href: 'https://www.linkedin.com/in/vikash-kumar-verma/', label: 'LinkedIn', aria: 'LinkedIn Profile' },
      { href: 'https://x.com/RajaVicky007', label: 'Twitter/X', aria: 'Twitter/X Profile' },
    ],
    profilePhoto: {
      src: '/profile.jpg',
      alt: 'Vikash Kumar profile',
    },
    coverLetter: `Dear Hiring Manager,\n\nWith over 8 years of experience as a frontend-focused software engineer, I bring a passion for building high-impact, user-centric applications. My journey spans IoT platforms, medical imaging tools, and large-scale performance monitoring systems. At Catchpoint, I led development for performance dashboards and real-time analytics using React and GraphQL. At Accure, I contributed to advanced UI workflows for diagnostic imaging, and at Techchefs, I integrated smart home interfaces via RESTful APIs.\n\nCurrently at EPAM Systems, I collaborate with cross-functional teams on fintech and fraud prevention initiatives at the London Stock Exchange Group. I also previously worked on internal Retool apps for Uber Eats store onboarding.\n\nI'm a firm believer in clean code, thoughtful architecture, and continuous improvement through mentorship and research. I’d love the opportunity to bring this mindset to your team.\n\nSincerely,\nVikash Kumar`,
    aboutSection: {
      title: 'About Me',
      description: 'Senior engineer and team lead at EPAM Systems with 9+ years of frontend development experience, delivering scalable and accessible web apps in fintech, healthcare, and performance domains using React, TypeScript, and modern web stacks.',
    },
    scrollDown: 'Scroll Down',
  },
  skills: {
    tabs: [
      { label: 'Frontend', key: 'frontend' },
      { label: 'Backend', key: 'backend' },
      { label: 'DevOps/Deployment', key: 'devops' },
      { label: 'Testing', key: 'testing' },
      { label: 'AI/GenAI', key: 'ai' },
      { label: 'Others', key: 'others' },
    ],
    items: [
      { name: 'React', tab: 'frontend', proficiency: 95 },
      { name: 'Next.js', tab: 'frontend', proficiency: 90 },
      { name: 'TypeScript', tab: 'frontend', proficiency: 90 },
      { name: 'TailwindCSS', tab: 'frontend', proficiency: 85 },
      { name: 'Design Systems', tab: 'frontend', proficiency: 85 },
      { name: 'Accessibility', tab: 'frontend', proficiency: 80 },
      { name: 'Node.js', tab: 'backend', proficiency: 85 },
      { name: 'Express', tab: 'backend', proficiency: 80 },
      { name: 'MongoDB', tab: 'backend', proficiency: 80 },
      { name: 'PostgreSQL', tab: 'backend', proficiency: 70 },
      { name: 'REST', tab: 'backend', proficiency: 85 },
      { name: 'GraphQL', tab: 'backend', proficiency: 75 },
      { name: 'Docker', tab: 'devops', proficiency: 80 },
      { name: 'GitHub Actions', tab: 'devops', proficiency: 75 },
      { name: 'GitLab', tab: 'devops', proficiency: 70 },
      { name: 'Vercel', tab: 'devops', proficiency: 85 },
      { name: 'Netlify', tab: 'devops', proficiency: 80 },
      { name: 'Helm', tab: 'devops', proficiency: 65 },
      { name: 'Kubernetes', tab: 'devops', proficiency: 55 },
      { name: 'Terraform', tab: 'devops', proficiency: 65 },
      { name: 'Jest', tab: 'testing', proficiency: 80 },
      { name: 'React Testing Library', tab: 'testing', proficiency: 75 },
      { name: 'Cypress', tab: 'testing', proficiency: 70 },
      { name: 'GPT-4 API', tab: 'ai', proficiency: 70 },
      { name: 'LangChain', tab: 'ai', proficiency: 65 },
      { name: 'RAG architecture basics', tab: 'ai', proficiency: 60 },
      { name: 'Prompt engineering', tab: 'ai', proficiency: 70 },
      { name: 'Git', tab: 'others', proficiency: 90 },
      { name: 'Webpack', tab: 'others', proficiency: 70 },
      { name: 'ESLint', tab: 'others', proficiency: 85 },
      { name: 'Storybook', tab: 'others', proficiency: 75 },
      { name: 'Firebase', tab: 'others', proficiency: 75 },
      { name: 'Retool', tab: 'others', proficiency: 65 },
    ],
    proficiencyTitle: 'Tech Stack Proficiency',
  },
  experience: [
    {
      year: '2024',
      color: 'blue',
      title: 'Lead Software Engineer',
      org: 'EPAM Systems',
      time: 'Oct 2024 – Present · Bengaluru, Karnataka, India (Hybrid)',
      details: [
        'Leading cross-functional teams to deliver scalable software products.',
        'Collaborated with Uber to optimize Retool apps for store onboarding in UberEATS.',
        'Currently building financial security tools for London Stock Exchange Group (LSEG) to prevent fraud and ensure regulatory compliance.',
        'Skills: Leadership, Retool, Fintech, Fraud Detection, Cross-team Collaboration',
      ],
    },
    {
      year: '2021',
      color: 'blue',
      title: 'Software Engineer III',
      org: 'Catchpoint',
      time: 'Dec 2021 – Oct 2024 · Bangalore Urban, Karnataka, India',
      details: [
        'Delivered performance analytics dashboards for real-time internet monitoring.',
        'Developed reusable UI components using React, Apollo GraphQL, and Redux.',
        'Mentored junior developers and conducted code reviews to maintain code quality.',
      ],
    },
    {
      year: '2019',
      color: 'blue',
      title: 'Software Engineer II',
      org: 'Catchpoint',
      time: 'Jun 2019 – Nov 2021 · Bengaluru, Karnataka, India',
      details: [
        'Built scalable, real-time interfaces for customer-facing dashboards.',
        'Enhanced performance visualization tools using GraphQL and React.',
      ],
    },
    {
      year: '2018',
      color: 'blue',
      title: 'Software Engineer',
      org: 'Accure Inc.',
      time: 'Jun 2018 – May 2019 · Bangalore',
      details: [
        'Developed intuitive UIs for medical imaging and diagnostics platforms.',
        'Collaborated with medical experts to build accessible interfaces.',
      ],
    },
    {
      year: '2016',
      color: 'blue',
      title: 'Associate Software Engineer',
      org: 'TechChefs Software Pvt Ltd',
      time: 'Jul 2016 – Jun 2018 · Bangalore',
      details: [
        'Contributed to smart home and IoT dashboard development.',
        'Worked on data visualization and REST API integrations.',
      ],
    },
  ],
  education: [
    {
      year: '2015',
      color: 'purple',
      title: 'BTECH (CSE)',
      org: 'Future Institute of Engineering And Management, Kolkata',
      time: 'June 2011 — June 2015',
      details: ['CGPA: 7.53'],
    },
    {
      year: '2011',
      color: 'purple',
      title: 'Engineering Exam Preparation',
      org: 'Vision Classes Patna',
      time: 'June 2009 — April 2011',
      details: [],
    },
    {
      year: '2009',
      color: 'purple',
      title: 'Intermediate (Science)',
      org: 'S B A N College Darheta Ladi',
      time: '2007 — 2009',
      details: ['68.6%'],
    },
    {
      year: '2007',
      color: 'purple',
      title: 'Metric',
      org: 'Pravesika High School Shakurabad',
      time: '2006 — 2007',
      details: ['67.6%'],
    },
  ],
  projects: [
    {
      title: 'E-Commerce Platform',
      description: 'Full-stack commerce platform with real-time inventory, secure payments, and a responsive admin panel. Built with React, Node.js, and MongoDB.',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
      demoLink: '#',
      githubLink: '#',
    },
    {
      title: 'Task Management App',
      description: 'Team-based task management system with Kanban boards, real-time updates, and cloud sync. Powered by Firebase and TypeScript.',
      image: 'https://images.unsplash.com/photo-1540350394557-8d14678e7f91?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'TypeScript', 'Firebase', 'Tailwind'],
      demoLink: '#',
      githubLink: '#',
    },
    {
      title: 'AI-Powered Analytics',
      description: 'Interactive dashboard offering AI insights, visualizations, and predictive metrics for business KPIs using GPT and TensorFlow.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
      tags: ['React', 'Python', 'TensorFlow', 'D3.js'],
      demoLink: '#',
      githubLink: '#',
    },
  ],
  testimonials: [
    {
      quote: 'Vikash is a detail-oriented engineer who consistently delivers scalable, maintainable solutions. A strong leader and a reliable teammate.',
      name: 'Ankit Sharma',
      title: 'Engineering Manager, Catchpoint',
    },
    {
      quote: 'Collaborating with Vikash was a masterclass in problem-solving and teamwork. He always brought fresh ideas to the table.',
      name: 'Priya Singh',
      title: 'Lead Developer, Accure Inc.',
    },
    {
      quote: 'Vikash’s leadership and frontend expertise have significantly accelerated our project delivery timelines.',
      name: 'Rahul Verma',
      title: 'Project Manager, EPAM Systems',
    },
  ],
  awards: [
    {
      icon: 'trophy',
      title: 'Hackathon Winner',
      description: 'Won multiple internal hackathons at Catchpoint for building advanced dashboards and performance tools.',
      date: '2022, 2023',
    },
    {
      icon: 'star',
      title: 'Employee of the Month',
      description: 'Recognized for innovation and ownership at Accure Inc. while working on mission-critical medical software.',
      date: '2019',
    },
    {
      icon: 'academicCap',
      title: 'AI & ML Course Completion',
      description: 'Completed multiple AI/ML certifications demonstrating continuous learning and future-tech adaptability.',
      date: '2021',
    },
  ],
  certifications: [
    {
      name: 'AWS Certified Solutions Architect',
      org: 'Amazon Web Services',
      year: '2022',
    },
    {
      name: 'Google Professional Cloud Developer',
      org: 'Google Cloud',
      year: '2021',
    },
    {
      name: 'Scrum Master Certified (SMC)',
      org: 'Scrum Alliance',
      year: '2020',
    },
  ],
  contact: {
    heading: 'Contact',
    thankYou: 'Thanks for reaching out! I’ll get back to you shortly.',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send Message',
  },
  projectsSection: {
    title: 'Featured Projects',
    description: 'A curated collection of projects that showcase my technical capabilities, design thinking, and business impact.',
  },
};

export default content;
